### ISSUE TITLE
troubles with Jmol Widget

### ISSUE THREAD

**Issue by ghost** [romerogroup/Crystallography#1]
Hi,
thanks for this nice suite of jupyter notebook. I am really interested in making them run.
However I come across some problems already in the introduction, at the point where a Jmol widget should be loaded.
I get the following msg : "Error connecting to server: https://chemapps.stolaf.edu/jmol/jsmol/php/jsmol.php?
call=getRawDataFromDatabase&database=_&query=https%3A%2F%2Fchemapps.stotlaf.edu%2Fjmol%2Fj2s%2Fcore%2Fpackage.js

How can I fix this problem ?
Thanks for your help
Claire

**Comment by fjfarah218** [comment]
Hi,

Thanks for pointing this out to us. It actually seems like there isn't a problem on your end - this is a new issue that has started coming up on all of our computers too. Since that server clearly exists, there must be an error with how the widget_jsmol package is querying it. We're passing this issue along to their GitHub: https://github.com/osscar-org/widget-jsmol/issues

I'll keep posting updates.

-Freddy

**Comment by fjfarah218** [comment]
The issue is fixed. We will continue to add/improve chapters, but you are welcome to begin the course. Feedback is always appreciated!
